language: minimal
dist: bionic
addons:
  snaps:
    - name: snapcraft
      channel: beta/remote-build
      confinement: classic
env:
  global:
    - SOLVESPACE_REPO="https://github.com/ppd1990/solvespace.git"
script:
  - git clone -b snap "$SOLVESPACE_REPO" solvespace
  - openssl aes-256-cbc -K $encrypted_5696ff3a6122_key -iv $encrypted_5696ff3a6122_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mkdir -p $HOME/.local/share/snapcraft/launchpad && mv launchpad-credentials $HOME/.local/share/snapcraft/launchpad/credentials
  - mkdir .snapcraft && mv snapcraft.cfg .snapcraft/snapcraft.cfg
  - mv remote-build-key "$HOME/remote-build-key" && chmod 600 "$HOME/remote-build-key"
  - printf "%s\n" "Host launchpad.net" "  IdentityFile $HOME/.ssh/remote-build-key" "  StrictHostKeyChecking accept-new" "  LogLevel ERROR" >> ~/.ssh/config
  - solvespace/pkg/snap/build.sh remote-build --user ppd --accept-public-upload
  - ls -al solvespace/pkg/snap/*.snap
  