language: minimal
dist: bionic
addons:
  snaps:
    - name: snapcraft
      channel: beta/remote-build
      confinement: classic
env:
  global:
    - SOLVESPACE_REPO="https://github.com/ppd1990/solvespace.git"
script:
  - git clone -b snap "$SOLVESPACE_REPO" solvespace
  - openssl aes-256-cbc -K $encrypted_5696ff3a6122_key -iv $encrypted_5696ff3a6122_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mkdir -p $HOME/.local/share/snapcraft/launchpad && mv launchpad-credentials $HOME/.local/share/snapcraft/launchpad/credentials
  - mv remote-build-key "$HOME/.ssh/id_rsa" && chmod 600 "$HOME/.ssh/id_rsa"
  - printf "%s\n" "  StrictHostKeyChecking no" >> ~/.ssh/config
  - travis_wait solvespace/pkg/snap/build.sh remote-build --user ppd --accept-public-upload --arch=amd64
deploy:
  provider: snap
  skip_cleanup: true
  snap: solvespace/pkg/snap/*.snap
  on:
    branch: master
  